/**/*:
  ros__parameters:
    network_interface: "network_bridge::UdpInterface"
  
    default_rate: 100.0

    default_zstd_level: 3

    publish_stale_data: False

    # publish_namespace: "/network_bridge"

    service_servers:
      - "/set_max_car_speed"
      - "/ghost/request"
      - "/trajectory/raceline_override"
      - "/trajectory/state_override"
      - "/trajectory/parameter_override"
      - "/trajectory/opponent_states_request"

    "/set_max_car_speed.type": "iac_msgs/srv/SetFloat32"
    "/set_max_car_speed.remote_name": "/set_max_car_speed"
    "/set_max_car_speed.timeout_ms": 1000

    "/ghost/request.type": "planning_msgs/srv/GhostCarCommand"
    "/ghost/request.remote_name": "/ghost/request"
    "/ghost/request.timeout_ms": 1000

    "/trajectory/raceline_override.type": "iac_msgs/srv/SetFloat32"
    "/trajectory/raceline_override.remote_name": "/trajectory/raceline_override"
    "/trajectory/raceline_override.timeout_ms": 1000

    "/trajectory/state_override.type": "planning_msgs/srv/SetString"
    "/trajectory/state_override.remote_name": "/trajectory/state_override"
    "/trajectory/state_override.timeout_ms": 1000

    "/trajectory/parameter_override.type": "planning_msgs/srv/SetString"
    "/trajectory/parameter_override.remote_name": "/trajectory/parameter_override"
    "/trajectory/parameter_override.timeout_ms": 1000

    "/trajectory/opponent_states_request.type": "planning_msgs/srv/TacticalStatesCommand"
    "/trajectory/opponent_states_request.remote_name": "/trajectory/opponent_states_request"
    "/trajectory/opponent_states_request.timeout_ms": 1000
